[package]
name = "sdk"
version = "0.1.0"
authors = ["xgxzj <gongxun.xia@upai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fail = "0.4"